run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocyclo
    - gocritic
    - revive
    - gosec
    - unconvert
    - unparam
    - prealloc

  disable:
    - funlen
    - lll

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

      - name: package-comments
        severity: warning
        disabled: false

  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
    - examples

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
